name: Actions Workflow

on:
  push:
    branches:
      - master
      - 'feature/*' # matches feature/feat1
      - 'feature/**' #Matches feature/feat/anything
      - '!feature/featC' #excludes featC
    tags:
      - v1.*
    paths:
      - '**.js' #only run when a .js file is pushed. 

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files after checkout
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}" 
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Crayton
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
